### ISSUE TITLE
Make into Multiplatform library

### ISSUE THREAD

**Issue by Wavesonics** [AdrianKuta/Tree-Collection#10]
I don't think you're using anything JVM specific that the kotlin std lib doesn't have, so it'd probably be a matter of setting up the gradle plugin, and swapping out some imports.

**Comment by AdrianKuta** [comment]
@Wavesonics 
Better late than never :D 
Thank you for suggestion. I will convert this code to kotlin multiplatform library.
Work has been started 🤞
