### ISSUE TITLE
Parent not set for nodes

### ISSUE THREAD

**Issue by aartiPl** [AdrianKuta/Tree-Collection#21]
I have noticed that the parent is not set in the nodes. Here is the simple test case:

```kotlin
val root = tree("Root") {
    child("Posix") {
        child("debianish") {
            child("Ubuntu") {
                child("v20.04")
            }
        }
        child("macos") {
            child("BigSur")
        }
    }
}

fun main() {
    println(root.prettyString())
    val ubuntu = root.find { it.value == "Ubuntu" }
    println(ubuntu?.prettyString())

    val path = mutableListOf<String>()

    var level = ubuntu
    while(level?.parent != null) {
        path += level.value
        level = level.parent
    }

    println("Path: $path")
}
```

I expect the 'parent' to be set for every node but the root, but apparently, it is not. I got an empty path as a result:

```
Path: []
```

Feature requests :-)
* provide the method path, which will give a path from the top to the given node (as in the example above)
* you can get some more inspiration at https://github.com/Scalified/tree, but you have probably already seen it.

BTW. Thanks for the nice library!

**Comment by AdrianKuta** [comment]
Thank you for feedback!
🚀 v3.0.1 this version fixes described issues
All comments are welcome. Because this is not a commercial project, but just a hobby and new things will rather be added on request or if I need them myself 😄
